trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DEV

stages:
- stage: Deploy
  jobs:
  - job: DeployContainer
    steps:
    - script: |
        echo "Fetching latest image from ACR"
        az acr login --name $(ACR_NAME)
        az containerapp update --name $(CONTAINER_APP_NAME) --resource-group $(RESOURCE_GROUP) --image $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
      displayName: 'Deploy Image to Azure Container Apps'
